version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /tools/mock-data-studio
    schedule:
      interval: weekly
    groups:
      mock-data-studio-dependencies:
        patterns:
          - "*"
