include:
  - path:
      - compose/base.yml
      - compose/infra/mysql/cluster.yml
      - compose/infra/redis/cluster.yml
      - compose/infra/kafka/cluster.yml
      - compose/infra/elasticsearch/cluster.yml
      - compose/infra/garage/cluster.yml
      - compose/infra/nacos/cluster.yml
      - compose/infra/mailhog.yml
      - compose/infra/mock-data-studio/common.yml
      - compose/infra/mock-data-studio/cluster.yml
      - compose/runtime/services/cluster.yml
      - compose/runtime/edge/cluster.yml
      - compose/runtime/mock-data-studio/common.yml
      - compose/runtime/mock-data-studio/cluster.yml
