security:
  jwt:
    issuer: community-auth
    access-token-audience: community-api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

community:
  metrics:
    basic-auth:
      username: prometheus
