-- Combined schema for local MySQL init (community + im_core).
--
-- This file is generated by merging the following scripts (order preserved):
-- - 005_schema_shared.sql
-- - 010_schema_identity.sql
-- - 015_schema_growth.sql
-- - 020_schema_content.sql
-- - 025_schema_social.sql
-- - 030_schema_message.sql
-- - 031_schema_im_core.sql
-- - 040_schema_search.sql
-- - 090_seed_identity.sql
--
-- NOTE: Database/user creation still lives in 001_create_databases.sh.

-- --------------------------------------------------------------------
-- Source: 005_schema_shared.sql
-- --------------------------------------------------------------------
-- Shared schema (community): outbox + HTTP idempotency.
--
-- Notes:
-- - Modular monolith uses a single schema `community`.
-- - These tables are cross-cutting and shared by multiple modules.

use community;

-- Outbox (reliable event delivery) - shared SSOT.
create table if not exists outbox_event (
  id bigint auto_increment primary key,
  event_id varchar(64) not null,
  topic varchar(255) not null,
  event_key varchar(255) not null,
  payload mediumtext not null,
  status varchar(32) not null,
  retry_count int not null default 0,
  next_retry_at timestamp null default null,
  last_error varchar(255),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  unique key uk_outbox_event_id (event_id),
  index idx_outbox_status_next (status, next_retry_at, id)
);

-- Outbox lease recover / cleanup indexes（idempotent）
set @idx_outbox_status_updated := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'outbox_event'
    and index_name = 'idx_outbox_status_updated'
);
set @sql := if(@idx_outbox_status_updated = 0, 'create index idx_outbox_status_updated on outbox_event(status, updated_at, id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_outbox_status_created := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'outbox_event'
    and index_name = 'idx_outbox_status_created'
);
set @sql := if(@idx_outbox_status_created = 0, 'create index idx_outbox_status_created on outbox_event(status, created_at, id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- HTTP write idempotency（SSOT=DB）：same (operation, user_id, idem_key) executes side effects once.
create table if not exists http_idempotency (
  id bigint auto_increment primary key,
  operation varchar(64) not null,
  user_id int not null,
  idem_key varchar(128) not null,
  status varchar(16) not null,
  response_json mediumtext null,
  processing_expires_at timestamp null,
  success_expires_at timestamp null,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null default current_timestamp on update current_timestamp,
  unique key uk_http_idem (operation, user_id, idem_key),
  key idx_http_idem_processing_expires (processing_expires_at, id),
  key idx_http_idem_success_expires (success_expires_at, id)
);


-- --------------------------------------------------------------------
-- Source: 010_schema_identity.sql
-- --------------------------------------------------------------------
-- Identity schema (keep in MYSQL_DATABASE=community for P0).
-- NOTE:
-- - 身份域数据所有权已收敛到 user-service；
-- - auth-service 已不再直连 MySQL（通过调用 user-service internal API 完成鉴权/注册/激活/重置密码等）。

use community;

create table if not exists user (
  id int auto_increment primary key,
  username varchar(255) not null,
  password varchar(255),
  salt varchar(255),
  email varchar(255),
  type int default 0,
  status int default 0,
  activation_code varchar(255),
  header_url varchar(255),
  create_time timestamp null default current_timestamp,
  score int not null default 0,
  mute_until timestamp null default null,
  ban_until timestamp null default null
);

-- refresh token（SSOT=DB）：auth-service 不直连 MySQL，改由 user-service 托管会话状态
-- 注意：只存 token_hash（SHA-256 hex），避免明文凭据落库
create table if not exists auth_refresh_token (
  token_hash char(64) primary key,
  user_id int not null,
  family_id varchar(64) not null,
  expires_at timestamp not null,
  revoked_at timestamp null default null,
  created_at timestamp null default current_timestamp,
  key idx_refresh_family (family_id, expires_at),
  key idx_refresh_user (user_id, expires_at)
);

-- Compatibility upgrade: add moderation columns for existing DBs (manual re-run scenario).
set @has_mute_until := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'user'
    and column_name = 'mute_until'
);
set @sql := if(@has_mute_until = 0, 'alter table user add column mute_until timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_score := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'user'
    and column_name = 'score'
);
set @sql := if(@has_score = 0, 'alter table user add column score int not null default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_ban_until := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'user'
    and column_name = 'ban_until'
);
set @sql := if(@has_ban_until = 0, 'alter table user add column ban_until timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- user-service Kafka 消费幂等（处罚命令等）：以 event_id 唯一约束为准（insert-first）。
create table if not exists user_consumed_event (
  id bigint auto_increment primary key,
  event_id varchar(64) not null,
  consumed_at timestamp not null default current_timestamp,
  unique key uk_user_consumed_event_id (event_id),
  index idx_user_consumed_event_at (consumed_at)
);


-- --------------------------------------------------------------------
-- Source: 015_schema_growth.sql
-- --------------------------------------------------------------------
-- Growth schema (points/levels/leaderboard) in identity DB (community).
-- NOTE: 作为“成长体系”的 SSOT，当前仅落地最小可用：
-- - user.score：累计积分（用于等级与榜单）
-- - user_score_log：事件幂等与积分流水（event_id 唯一）

use community;

create table if not exists user_score_log (
  id bigint auto_increment primary key,
  user_id int not null,
  event_id varchar(64) not null,
  event_type varchar(64) not null,
  delta int not null,
  create_time timestamp null default current_timestamp,
  unique key uk_event_id (event_id),
  key idx_user_time (user_id, create_time)
);



-- --------------------------------------------------------------------
-- Source: 020_schema_content.sql
-- --------------------------------------------------------------------
-- Content schema (community): posts + comments.

use community;

create table if not exists discuss_post (
  id int auto_increment primary key,
  user_id int,
  category_id int default null,
  title varchar(255),
  content text,
  type int default 0,
  status int default 0,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default null,
  edit_count int default 0,
  deleted_by int default 0,
  deleted_reason varchar(255) default '',
  deleted_time timestamp null default null,
  comment_count int default 0,
  score double default 0
);

create table if not exists comment (
  id int auto_increment primary key,
  user_id int,
  entity_type int,
  entity_id int,
  target_id int default 0,
  content text,
  status int default 0,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default null,
  edit_count int default 0,
  deleted_by int default 0,
  deleted_reason varchar(255) default '',
  deleted_time timestamp null default null
);

-- taxonomy: categories + tags (Discourse-like)
create table if not exists category (
  id int auto_increment primary key,
  name varchar(64) not null,
  description varchar(255) default '',
  position int default 0,
  create_time timestamp null default current_timestamp,
  unique key uk_category_name (name)
);

create table if not exists tag (
  id int auto_increment primary key,
  name varchar(64) not null,
  create_time timestamp null default current_timestamp,
  unique key uk_tag_name (name)
);

create table if not exists post_tag (
  post_id int not null,
  tag_id int not null,
  create_time timestamp null default current_timestamp,
  primary key (post_id, tag_id)
);

-- moderation: reports + actions (MVP)
create table if not exists report (
  id int auto_increment primary key,
  reporter_id int not null,
  target_type int not null,
  target_id int not null,
  reason varchar(64) not null,
  detail varchar(512) default '',
  status int default 0,
  create_time timestamp null default current_timestamp,
  unique key uk_report_dedupe (reporter_id, target_type, target_id)
);

create table if not exists moderation_action (
  id int auto_increment primary key,
  report_id int default null,
  actor_id int not null,
  action varchar(32) not null,
  reason varchar(255) default '',
  duration_seconds int default 0,
  create_time timestamp null default current_timestamp
);

-- bookmarks/subscriptions (MVP)
create table if not exists post_bookmark (
  user_id int not null,
  post_id int not null,
  create_time timestamp null default current_timestamp,
  primary key (user_id, post_id)
);

create table if not exists user_subscription_category (
  user_id int not null,
  category_id int not null,
  create_time timestamp null default current_timestamp,
  primary key (user_id, category_id)
);

-- Compatibility upgrade: add missing column for existing DBs (manual re-run scenario).
set @has_category_id := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'category_id'
);
set @sql := if(@has_category_id = 0, 'alter table discuss_post add column category_id int default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- Compatibility upgrade: add edit/update/delete meta columns for existing DBs.
set @has_update_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'update_time'
);
set @sql := if(@has_update_time = 0, 'alter table discuss_post add column update_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_edit_count := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'edit_count'
);
set @sql := if(@has_edit_count = 0, 'alter table discuss_post add column edit_count int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_deleted_by := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'deleted_by'
);
set @sql := if(@has_deleted_by = 0, 'alter table discuss_post add column deleted_by int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_deleted_reason := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'deleted_reason'
);
set @sql := if(@has_deleted_reason = 0, 'alter table discuss_post add column deleted_reason varchar(255) default ''''', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_deleted_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'deleted_time'
);
set @sql := if(@has_deleted_time = 0, 'alter table discuss_post add column deleted_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_update_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'update_time'
);
set @sql := if(@has_comment_update_time = 0, 'alter table comment add column update_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_edit_count := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'edit_count'
);
set @sql := if(@has_comment_edit_count = 0, 'alter table comment add column edit_count int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_deleted_by := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'deleted_by'
);
set @sql := if(@has_comment_deleted_by = 0, 'alter table comment add column deleted_by int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_deleted_reason := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'deleted_reason'
);
set @sql := if(@has_comment_deleted_reason = 0, 'alter table comment add column deleted_reason varchar(255) default ''''', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_deleted_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'deleted_time'
);
set @sql := if(@has_comment_deleted_time = 0, 'alter table comment add column deleted_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- Indexes (idempotent)
set @idx_discuss_post_user_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'discuss_post'
    and index_name = 'idx_discuss_post_user_id'
);
set @sql := if(@idx_discuss_post_user_id = 0, 'create index idx_discuss_post_user_id on discuss_post(user_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_discuss_post_category_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'discuss_post'
    and index_name = 'idx_discuss_post_category_id'
);
set @sql := if(@idx_discuss_post_category_id = 0, 'create index idx_discuss_post_category_id on discuss_post(category_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- report indexes (idempotent)
set @idx_report_status := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'report'
    and index_name = 'idx_report_status'
);
set @sql := if(@idx_report_status = 0, 'create index idx_report_status on report(status, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_report_target := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'report'
    and index_name = 'idx_report_target'
);
set @sql := if(@idx_report_target = 0, 'create index idx_report_target on report(target_type, target_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- moderation_action indexes (idempotent)
set @idx_moderation_action_report := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'moderation_action'
    and index_name = 'idx_moderation_action_report'
);
set @sql := if(@idx_moderation_action_report = 0, 'create index idx_moderation_action_report on moderation_action(report_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_moderation_action_actor := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'moderation_action'
    and index_name = 'idx_moderation_action_actor'
);
set @sql := if(@idx_moderation_action_actor = 0, 'create index idx_moderation_action_actor on moderation_action(actor_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- bookmark/subscription indexes (idempotent)
set @idx_post_bookmark_post := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'post_bookmark'
    and index_name = 'idx_post_bookmark_post'
);
set @sql := if(@idx_post_bookmark_post = 0, 'create index idx_post_bookmark_post on post_bookmark(post_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_user_sub_category_user := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'user_subscription_category'
    and index_name = 'idx_user_sub_category_user'
);
set @sql := if(@idx_user_sub_category_user = 0, 'create index idx_user_sub_category_user on user_subscription_category(user_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_comment_entity := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'comment'
    and index_name = 'idx_comment_entity'
);
set @sql := if(@idx_comment_entity = 0, 'create index idx_comment_entity on comment(entity_type, entity_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_post_tag_post_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'post_tag'
    and index_name = 'idx_post_tag_post_id'
);
set @sql := if(@idx_post_tag_post_id = 0, 'create index idx_post_tag_post_id on post_tag(post_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_post_tag_tag_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'post_tag'
    and index_name = 'idx_post_tag_tag_id'
);
set @sql := if(@idx_post_tag_tag_id = 0, 'create index idx_post_tag_tag_id on post_tag(tag_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- Default categories for dev (idempotent)
insert ignore into category(name, description, position) values
  ('公告', '官方公告/规则', 0),
  ('技术', '技术讨论/问题求助', 10),
  ('兴趣', '兴趣分享/作品展示', 20);


-- --------------------------------------------------------------------
-- Source: 025_schema_social.sql
-- --------------------------------------------------------------------
-- Social schema (community): likes + follows + blocks.

use community;

create table if not exists social_like (
  user_id bigint not null,
  entity_type int not null,
  entity_id bigint not null,
  created_at timestamp not null default current_timestamp,
  primary key (user_id, entity_type, entity_id),
  index idx_like_entity (entity_type, entity_id)
);

-- social_like 扫描索引（idempotent）：用于按 (entity_type, entity_id, user_id) keyset 分页（运维排查/历史遗留 scan RPC）
set @idx_like_entity_user := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'social_like'
    and index_name = 'idx_like_entity_user'
);
set @sql := if(@idx_like_entity_user = 0, 'create index idx_like_entity_user on social_like(entity_type, entity_id, user_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- 用户获赞数（计数 SSOT）：由写路径在“新增点赞/取消点赞”时原子增减。
create table if not exists social_user_like_count (
  user_id bigint not null primary key,
  like_count bigint not null default 0,
  updated_at timestamp not null default current_timestamp on update current_timestamp
);

create table if not exists social_follow (
  user_id bigint not null,
  entity_type int not null,
  entity_id bigint not null,
  created_at timestamp not null default current_timestamp,
  primary key (user_id, entity_type, entity_id),
  index idx_follow_followee (user_id, entity_type, created_at, entity_id),
  index idx_follow_follower (entity_type, entity_id, created_at, user_id)
);

create table if not exists social_block (
  user_id bigint not null,
  target_user_id bigint not null,
  created_at timestamp not null default current_timestamp,
  primary key (user_id, target_user_id),
  index idx_block_user_created (user_id, created_at)
);


-- --------------------------------------------------------------------
-- Source: 030_schema_message.sql
-- --------------------------------------------------------------------
-- Message schema (community): message + consumed_event.

use community;

create table if not exists message (
  id int auto_increment primary key,
  from_id int,
  to_id int,
  conversation_id varchar(255),
  content varchar(4000),
  status int default 0,
  create_time timestamp null default current_timestamp
);

create table if not exists consumed_event (
  id int auto_increment primary key,
  event_id varchar(64) unique,
  consumed_at timestamp null default current_timestamp
);

create index idx_consumed_event_at on consumed_event(consumed_at, id);

create index idx_message_conversation on message(conversation_id);
create index idx_message_to_status on message(to_id, status);


-- --------------------------------------------------------------------
-- Source: 031_schema_im_core.sql
-- --------------------------------------------------------------------
-- IM Core schema (im_core): room + private message (seq-based) + read watermarks.

use im_core;

create table if not exists im_room (
  room_id bigint primary key,
  name varchar(128),
  last_seq bigint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null default current_timestamp on update current_timestamp
);

create table if not exists im_room_member (
  room_id bigint not null,
  user_id int not null,
  role tinyint not null default 0,
  joined_at timestamp null default current_timestamp,
  primary key (room_id, user_id)
);

create index idx_im_room_member_user on im_room_member(user_id, room_id);

create table if not exists im_room_message (
  room_id bigint not null,
  seq bigint not null,
  message_id bigint not null,
  from_user_id int not null,
  content mediumtext not null,
  client_msg_id varchar(64) not null,
  created_at timestamp null default current_timestamp,
  primary key (room_id, seq),
  unique key uk_im_room_message_idempotency (room_id, from_user_id, client_msg_id),
  unique key uk_im_room_message_id (message_id)
);

create index idx_im_room_message_created_at on im_room_message(room_id, created_at, seq);

create table if not exists im_room_read_state (
  room_id bigint not null,
  user_id int not null,
  last_read_seq bigint not null default 0,
  updated_at timestamp null default current_timestamp on update current_timestamp,
  primary key (room_id, user_id)
);

create index idx_im_room_read_state_user on im_room_read_state(user_id, room_id);

create table if not exists im_conversation (
  conversation_id varchar(64) primary key,
  user_a int not null,
  user_b int not null,
  last_seq bigint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null default current_timestamp on update current_timestamp
);

create index idx_im_conversation_users on im_conversation(user_a, user_b, conversation_id);

create table if not exists im_private_message (
  conversation_id varchar(64) not null,
  seq bigint not null,
  message_id bigint not null,
  from_user_id int not null,
  to_user_id int not null,
  content mediumtext not null,
  client_msg_id varchar(64) not null,
  created_at timestamp null default current_timestamp,
  primary key (conversation_id, seq),
  unique key uk_im_private_message_idempotency (conversation_id, from_user_id, client_msg_id),
  unique key uk_im_private_message_id (message_id)
);

create index idx_im_private_message_to on im_private_message(to_user_id, conversation_id, seq);

create table if not exists im_conversation_read_state (
  conversation_id varchar(64) not null,
  user_id int not null,
  last_read_seq bigint not null default 0,
  updated_at timestamp null default current_timestamp on update current_timestamp,
  primary key (conversation_id, user_id)
);

create index idx_im_conversation_read_state_user on im_conversation_read_state(user_id, conversation_id);



-- --------------------------------------------------------------------
-- Source: 040_schema_search.sql
-- --------------------------------------------------------------------
-- Search schema (community): search service consumed-event table.

use community;

create table if not exists search_consumed_event (
  id int auto_increment primary key,
  event_id varchar(64) unique,
  consumed_at timestamp null default current_timestamp
);

create index idx_search_consumed_at on search_consumed_event(consumed_at, id);


-- --------------------------------------------------------------------
-- Source: 090_seed_identity.sql
-- --------------------------------------------------------------------
-- Seed for local dev/demo only.
-- Default user: username=aaa, password=aaa (legacy MD5+salt), status=1 (activated)

use community;

insert into user (id, username, password, salt, email, type, status, activation_code, header_url, create_time)
values
  (1, 'aaa', 'be5cdc88ad25c5aa86b9a9e1c3573e79', 'salt', 'aaa@example.com', 0, 1, 'ac', 'http://example.com/a.png', now()),
  (2, 'bbb', 'be5cdc88ad25c5aa86b9a9e1c3573e79', 'salt', 'bbb@example.com', 0, 1, 'ac', 'http://example.com/b.png', now()),
  (3, 'admin', 'be5cdc88ad25c5aa86b9a9e1c3573e79', 'salt', 'admin@example.com', 1, 1, 'ac', 'http://example.com/admin.png', now())
on duplicate key update username = values(username);

