-- Combined schema for local MySQL init (community + im_core).
--
-- This file is generated by merging the following scripts (order preserved):
-- - 005_schema_shared.sql
-- - 010_schema_identity.sql
-- - 015_schema_growth.sql
-- - 020_schema_content.sql
-- - 025_schema_social.sql
-- - 030_schema_message.sql
-- - 031_schema_im_core.sql
-- - 040_schema_search.sql
-- - 090_seed_identity.sql
--
-- NOTE: Database/user creation still lives in 001_create_databases.sh.

-- --------------------------------------------------------------------
-- Source: 005_schema_shared.sql
-- --------------------------------------------------------------------
-- Shared schema (community): outbox + HTTP idempotency.
--
-- Notes:
-- - Modular monolith uses a single schema `community`.
-- - These tables are cross-cutting and shared by multiple modules.

use community;

set names utf8mb4;

-- Outbox (reliable event delivery) - shared SSOT.
create table if not exists outbox_event (
  id bigint auto_increment primary key,
  event_id varchar(64) not null,
  topic varchar(255) not null,
  event_key varchar(255) not null,
  payload mediumtext not null,
  status varchar(32) not null,
  retry_count int not null default 0,
  next_retry_at timestamp null default null,
  last_error varchar(255),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  unique key uk_outbox_event_id (event_id),
  index idx_outbox_status_next (status, next_retry_at, id)
);

-- Outbox lease recover / cleanup indexes（idempotent）
set @idx_outbox_status_updated := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'outbox_event'
    and index_name = 'idx_outbox_status_updated'
);
set @sql := if(@idx_outbox_status_updated = 0, 'create index idx_outbox_status_updated on outbox_event(status, updated_at, id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_outbox_status_created := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'outbox_event'
    and index_name = 'idx_outbox_status_created'
);
set @sql := if(@idx_outbox_status_created = 0, 'create index idx_outbox_status_created on outbox_event(status, created_at, id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- HTTP write idempotency（SSOT=DB）：same (operation, user_id, idem_key) executes side effects once.
create table if not exists http_idempotency (
  id bigint auto_increment primary key,
  operation varchar(64) not null,
  user_id int not null,
  idem_key varchar(128) not null,
  status varchar(16) not null,
  response_json mediumtext null,
  processing_expires_at timestamp null,
  success_expires_at timestamp null,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null default current_timestamp on update current_timestamp,
  unique key uk_http_idem (operation, user_id, idem_key),
  key idx_http_idem_processing_expires (processing_expires_at, id),
  key idx_http_idem_success_expires (success_expires_at, id)
);

-- --------------------------------------------------------------------
-- Source: 007_schema_demo_metadata.sql
-- --------------------------------------------------------------------
-- Mock-data metadata sidecar tables (community).
--
-- Notes:
-- - Phase 1 keeps demo tracking in sidecar metadata tables.
-- - We deliberately avoid adding demo_batch_id columns to business tables.

use community;

create table if not exists demo_batch (
  id bigint auto_increment primary key,
  batch_key varchar(128) not null,
  batch_type varchar(64) not null,
  requested_by varchar(128) not null,
  status varchar(32) not null,
  summary_json mediumtext null,
  error_message varchar(255) null,
  created_at timestamp not null default current_timestamp,
  started_at timestamp null default null,
  finished_at timestamp null default null,
  unique key uk_demo_batch_key (batch_key),
  key idx_demo_batch_status_created (status, created_at, id)
);

create table if not exists demo_job (
  id bigint auto_increment primary key,
  batch_id bigint not null,
  job_key varchar(128) not null,
  job_type varchar(64) not null,
  status varchar(32) not null,
  summary_json mediumtext null,
  error_message varchar(255) null,
  created_at timestamp not null default current_timestamp,
  started_at timestamp null default null,
  finished_at timestamp null default null,
  unique key uk_demo_job_batch_key (batch_id, job_key),
  key idx_demo_job_batch_status (batch_id, status, id)
);

create table if not exists demo_batch_target (
  id bigint auto_increment primary key,
  batch_id bigint not null,
  entity_type varchar(64) not null,
  target_key varchar(255) not null,
  target_count int not null default 1,
  payload_json mediumtext null,
  created_at timestamp not null default current_timestamp,
  unique key uk_demo_batch_target (batch_id, entity_type, target_key),
  key idx_demo_batch_target_batch (batch_id, id)
);

create table if not exists demo_entity_ref (
  id bigint auto_increment primary key,
  batch_id bigint not null,
  entity_type varchar(64) not null,
  entity_key varchar(255) not null,
  created_at timestamp not null default current_timestamp,
  unique key uk_demo_entity_ref (batch_id, entity_type, entity_key),
  key idx_demo_entity_ref_batch (batch_id, id)
);


-- --------------------------------------------------------------------
-- Source: 010_schema_identity.sql
-- --------------------------------------------------------------------
-- Identity schema (keep in MYSQL_DATABASE=community for P0).
-- NOTE:
-- - 身份域数据所有权已收敛到 user 模块；
-- - auth 模块已不再直连 MySQL（通过调用 user 模块内部 API 完成鉴权/注册/邮箱验证/重置密码等）。

use community;

create table if not exists user (
  id int auto_increment primary key,
  username varchar(255) not null,
  password varchar(255),
  salt varchar(255),
  email varchar(255),
  type int default 0,
  status int default 0,
  header_url varchar(255),
  create_time timestamp null default current_timestamp,
  score int not null default 0,
  mute_until timestamp null default null,
  ban_until timestamp null default null,
  unique key uk_user_username (username),
  unique key uk_user_email (email)
);

-- refresh token（SSOT=DB）：auth 模块不直连 MySQL，改由 user 模块托管会话状态
-- 注意：只存 token_hash（SHA-256 hex），避免明文凭据落库
create table if not exists auth_refresh_token (
  token_hash char(64) primary key,
  user_id int not null,
  family_id varchar(64) not null,
  expires_at timestamp not null,
  revoked_at timestamp null default null,
  created_at timestamp null default current_timestamp,
  key idx_refresh_family (family_id, expires_at),
  key idx_refresh_user (user_id, expires_at)
);

-- Compatibility upgrade: add moderation columns for existing DBs (manual re-run scenario).
set @has_mute_until := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'user'
    and column_name = 'mute_until'
);
set @sql := if(@has_mute_until = 0, 'alter table user add column mute_until timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_score := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'user'
    and column_name = 'score'
);
set @sql := if(@has_score = 0, 'alter table user add column score int not null default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_ban_until := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'user'
    and column_name = 'ban_until'
);
set @sql := if(@has_ban_until = 0, 'alter table user add column ban_until timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_user_username_uk := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'user'
    and index_name = 'uk_user_username'
);
set @sql := if(@has_user_username_uk = 0, 'alter table user add constraint uk_user_username unique (username)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_user_email_uk := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'user'
    and index_name = 'uk_user_email'
);
set @sql := if(@has_user_email_uk = 0, 'alter table user add constraint uk_user_email unique (email)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- 用户处罚类事件幂等（历史遗留）：以 event_id 唯一约束为准（insert-first）。
create table if not exists user_consumed_event (
  id bigint auto_increment primary key,
  event_id varchar(64) not null,
  consumed_at timestamp not null default current_timestamp,
  unique key uk_user_consumed_event_id (event_id),
  index idx_user_consumed_event_at (consumed_at)
);


-- --------------------------------------------------------------------
-- Source: 015_schema_growth.sql
-- --------------------------------------------------------------------
-- Growth schema (points/levels/leaderboard) in identity DB (community).
-- NOTE: 作为“成长体系”的 SSOT，当前仅落地最小可用：
-- - user.score：累计积分（用于等级与榜单）
-- - user_score_log：事件幂等与积分流水（event_id 唯一）
-- - reward_account / reward_ledger：奖励余额账户与流水
-- - reward_grant_record：统一发放编排记录
-- - admin_reward_adjustment：后台手工调整审计

use community;

create table if not exists user_score_log (
  id bigint auto_increment primary key,
  user_id int not null,
  event_id varchar(64) not null,
  event_type varchar(64) not null,
  delta int not null,
  create_time timestamp null default current_timestamp,
  unique key uk_event_id (event_id),
  key idx_user_time (user_id, create_time)
);

create table if not exists reward_account (
  user_id int not null primary key,
  available_balance int not null default 0,
  frozen_balance int not null default 0,
  version int not null default 0,
  update_time timestamp null default current_timestamp
);

create table if not exists reward_ledger (
  id bigint auto_increment primary key,
  user_id int not null,
  event_id varchar(64) not null,
  event_type varchar(64) not null,
  delta int not null,
  balance_after int not null,
  frozen_balance_after int not null default 0,
  biz_key varchar(128) default null,
  source_module varchar(64) default null,
  remark varchar(255) default null,
  create_time timestamp null default current_timestamp,
  unique key uk_reward_ledger_event_id (event_id),
  key idx_reward_ledger_user_time (user_id, create_time)
);

create table if not exists wallet_account (
  account_id bigint auto_increment primary key,
  owner_type varchar(32) not null,
  owner_id bigint not null,
  account_type varchar(32) not null,
  balance bigint not null default 0,
  status varchar(16) not null,
  version bigint not null default 0,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_wallet_account_owner (owner_type, owner_id, account_type)
);

create table if not exists wallet_txn (
  txn_id bigint auto_increment primary key,
  request_id varchar(96) not null,
  txn_type varchar(32) not null,
  biz_type varchar(32) not null,
  biz_id varchar(96) not null,
  status varchar(16) not null,
  amount bigint not null,
  remark varchar(255) default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_wallet_txn_request (request_id)
);

create table if not exists wallet_entry (
  entry_id bigint auto_increment primary key,
  txn_id bigint not null,
  account_id bigint not null,
  direction varchar(8) not null,
  amount bigint not null,
  balance_after bigint not null,
  create_time timestamp null default current_timestamp,
  key idx_wallet_entry_txn (txn_id),
  key idx_wallet_entry_account_time (account_id, create_time)
);

create table if not exists recharge_order (
  order_id bigint auto_increment primary key,
  request_id varchar(96) not null,
  user_id bigint not null,
  amount bigint not null,
  status varchar(16) not null,
  channel varchar(32) default null,
  channel_order_id varchar(96) default null,
  remark varchar(255) default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_recharge_order_request (request_id),
  key idx_recharge_order_user_time (user_id, create_time)
);

create table if not exists withdraw_order (
  order_id bigint auto_increment primary key,
  request_id varchar(96) not null,
  user_id bigint not null,
  amount bigint not null,
  status varchar(16) not null,
  payee_account varchar(128) default null,
  failure_reason varchar(255) default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_withdraw_order_request (request_id),
  key idx_withdraw_order_user_time (user_id, create_time)
);

create table if not exists transfer_order (
  order_id bigint auto_increment primary key,
  request_id varchar(96) not null,
  from_user_id bigint not null,
  to_user_id bigint not null,
  amount bigint not null,
  status varchar(16) not null,
  remark varchar(255) default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_transfer_order_request (request_id),
  key idx_transfer_order_from_user_time (from_user_id, create_time),
  key idx_transfer_order_to_user_time (to_user_id, create_time)
);

create table if not exists wallet_admin_action (
  action_id bigint auto_increment primary key,
  request_id varchar(96) not null,
  actor_user_id bigint not null,
  target_account_id bigint not null,
  action_type varchar(32) not null,
  amount bigint not null,
  remark varchar(255) default null,
  create_time timestamp null default current_timestamp,
  unique key uk_wallet_admin_action_request (request_id),
  key idx_wallet_admin_action_target_time (target_account_id, create_time)
);

create table if not exists virtual_listing (
  listing_id bigint auto_increment primary key,
  seller_user_id int not null,
  title varchar(128) not null,
  description varchar(1000) not null,
  unit_price bigint not null,
  delivery_mode varchar(16) not null,
  stock_mode varchar(16) not null,
  stock_total int not null,
  stock_available int not null,
  min_purchase_quantity int not null,
  max_purchase_quantity int not null,
  status varchar(16) not null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp
);

create table if not exists virtual_inventory_unit (
  inventory_unit_id bigint auto_increment primary key,
  listing_id bigint not null,
  seller_user_id int not null,
  payload_type varchar(16) not null,
  payload_content varchar(4000) not null,
  status varchar(16) not null,
  reserved_order_id bigint default null,
  delivered_at timestamp null default null,
  create_time timestamp null default current_timestamp,
  key idx_virtual_inventory_listing_status (listing_id, status, inventory_unit_id)
);

create table if not exists virtual_order (
  order_id bigint auto_increment primary key,
  request_id varchar(96) not null,
  listing_id bigint not null,
  seller_user_id int not null,
  buyer_user_id int not null,
  quantity int not null,
  unit_price_snapshot bigint not null,
  total_amount bigint not null,
  delivery_mode_snapshot varchar(16) not null,
  listing_title_snapshot varchar(128) not null,
  status varchar(16) not null,
  escrow_txn_id bigint default null,
  release_txn_id bigint default null,
  refund_txn_id bigint default null,
  auto_confirm_at timestamp null default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_virtual_order_request (request_id),
  key idx_virtual_order_buyer_time (buyer_user_id, create_time),
  key idx_virtual_order_seller_time (seller_user_id, create_time),
  key idx_virtual_order_listing_status (listing_id, status),
  key idx_virtual_order_auto_confirm (status, auto_confirm_at)
);

create table if not exists virtual_delivery (
  delivery_id bigint auto_increment primary key,
  order_id bigint not null,
  seller_user_id int not null,
  delivery_type varchar(32) not null,
  delivery_content varchar(8000) not null,
  status varchar(16) not null,
  delivered_at timestamp null default null,
  create_time timestamp null default current_timestamp,
  key idx_virtual_delivery_order (order_id, delivery_id)
);

create table if not exists virtual_dispute (
  dispute_id bigint auto_increment primary key,
  order_id bigint not null,
  buyer_user_id int not null,
  seller_user_id int not null,
  status varchar(32) not null,
  reason varchar(255) not null,
  buyer_note varchar(1000) not null,
  seller_note varchar(1000) default null,
  resolution_type varchar(16) default null,
  resolved_by int default null,
  resolved_at timestamp null default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  key idx_virtual_dispute_order_status (order_id, status)
);

create table if not exists reward_grant_record (
  id bigint auto_increment primary key,
  grant_id varchar(64) not null,
  user_id int not null,
  grant_type varchar(64) not null,
  source_event_id varchar(64) not null,
  source_event_type varchar(64) not null,
  growth_delta int not null default 0,
  reward_delta int not null default 0,
  status varchar(32) not null,
  create_time timestamp null default current_timestamp,
  unique key uk_reward_grant_id (grant_id),
  key idx_reward_grant_user_time (user_id, create_time)
);

create table if not exists admin_reward_adjustment (
  id bigint auto_increment primary key,
  actor_user_id int not null,
  target_user_id int not null,
  asset_type varchar(32) not null,
  delta int not null,
  before_value int not null,
  after_value int not null,
  reason varchar(255) not null,
  confirm_token varchar(64) default null,
  create_time timestamp null default current_timestamp,
  key idx_admin_reward_adjustment_target_time (target_user_id, create_time),
  key idx_admin_reward_adjustment_actor_time (actor_user_id, create_time)
);

create table if not exists admin_reward_order_action (
  id bigint auto_increment primary key,
  order_id bigint not null,
  actor_user_id int not null,
  action varchar(16) not null,
  from_status varchar(16) not null,
  to_status varchar(16) not null,
  note varchar(255) not null,
  create_time timestamp null default current_timestamp,
  key idx_admin_reward_order_action_order_time (order_id, create_time),
  key idx_admin_reward_order_action_actor_time (actor_user_id, create_time)
);

create table if not exists growth_check_in (
  id bigint auto_increment primary key,
  user_id int not null,
  biz_date date not null,
  streak_count int not null,
  create_time timestamp null default current_timestamp,
  unique key uk_growth_check_in_user_date (user_id, biz_date),
  key idx_growth_check_in_user_date (user_id, biz_date)
);

create table if not exists task_template (
  task_code varchar(64) primary key,
  task_type varchar(32) not null,
  period_type varchar(16) not null,
  trigger_event_type varchar(64) not null,
  target_value int not null,
  reward_growth_delta int not null default 0,
  reward_balance_delta int not null default 0,
  claim_required tinyint(1) not null default 0,
  display_order int not null default 0,
  status varchar(16) not null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  key idx_task_template_trigger (trigger_event_type, status, display_order)
);

create table if not exists user_task_progress (
  id bigint auto_increment primary key,
  user_id int not null,
  task_code varchar(64) not null,
  period_key varchar(32) not null,
  current_value int not null,
  target_value int not null,
  status varchar(16) not null,
  reached_at timestamp null default null,
  claimed_at timestamp null default null,
  reward_grant_id varchar(64) default null,
  last_source_event_id varchar(64) default null,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_user_task_period (user_id, task_code, period_key),
  key idx_user_task_lookup (user_id, status, update_time)
);

create table if not exists user_task_event_log (
  id bigint auto_increment primary key,
  user_id int not null,
  task_code varchar(64) not null,
  period_key varchar(32) not null,
  source_event_id varchar(64) not null,
  create_time timestamp null default current_timestamp,
  unique key uk_user_task_event (user_id, task_code, period_key, source_event_id),
  key idx_user_task_event_lookup (user_id, task_code, period_key, create_time)
);

insert ignore into task_template(task_code, task_type, period_type, trigger_event_type, target_value, reward_growth_delta, reward_balance_delta, claim_required, display_order, status)
values
  ('DAILY_CHECK_IN', 'CHECK_IN', 'DAILY', 'DailyCheckIn', 1, 2, 1, 0, 10, 'ACTIVE'),
  ('DAILY_POST', 'CONTENT', 'DAILY', 'PostPublished', 1, 3, 1, 0, 20, 'ACTIVE'),
  ('WEEKLY_COMMENTER', 'CONTENT', 'WEEKLY', 'CommentCreated', 2, 4, 1, 0, 30, 'ACTIVE'),
  ('LIFETIME_RECEIVE_LIKE', 'SOCIAL', 'LIFETIME', 'LikeCreated', 3, 6, 2, 0, 40, 'ACTIVE');

create table if not exists reward_item (
  id bigint auto_increment primary key,
  item_name varchar(128) not null,
  item_desc varchar(255) default null,
  cost_balance int not null,
  stock int not null,
  per_user_limit int not null default 0,
  fulfillment_mode varchar(16) not null,
  status varchar(16) not null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  key idx_reward_item_status_sort (status, update_time)
);

create table if not exists reward_order (
  id bigint auto_increment primary key,
  redeem_request_id varchar(64) not null,
  user_id int not null,
  item_id bigint not null,
  status varchar(16) not null,
  cost_balance_snapshot int not null,
  fulfillment_mode_snapshot varchar(16) not null,
  item_name_snapshot varchar(128) not null,
  item_desc_snapshot varchar(255) default null,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default current_timestamp on update current_timestamp,
  unique key uk_reward_order_user_request (user_id, redeem_request_id),
  key idx_reward_order_user_time (user_id, create_time),
  key idx_reward_order_user_item_status (user_id, item_id, status)
);



-- --------------------------------------------------------------------
-- Source: 020_schema_content.sql
-- --------------------------------------------------------------------
-- Content schema (community): posts + comments.

use community;

create table if not exists discuss_post (
  id int auto_increment primary key,
  user_id int,
  category_id int default null,
  title varchar(255),
  content text,
  type int default 0,
  status int default 0,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default null,
  edit_count int default 0,
  deleted_by int default 0,
  deleted_reason varchar(255) default '',
  deleted_time timestamp null default null,
  comment_count int default 0,
  score double default 0
);

create table if not exists comment (
  id int auto_increment primary key,
  user_id int,
  entity_type int,
  entity_id int,
  target_id int default 0,
  content text,
  status int default 0,
  create_time timestamp null default current_timestamp,
  update_time timestamp null default null,
  edit_count int default 0,
  deleted_by int default 0,
  deleted_reason varchar(255) default '',
  deleted_time timestamp null default null
);

-- taxonomy: categories + tags (Discourse-like)
create table if not exists category (
  id int auto_increment primary key,
  name varchar(64) not null,
  description varchar(255) default '',
  position int default 0,
  create_time timestamp null default current_timestamp,
  unique key uk_category_name (name)
);

create table if not exists tag (
  id int auto_increment primary key,
  name varchar(64) not null,
  create_time timestamp null default current_timestamp,
  unique key uk_tag_name (name)
);

create table if not exists post_tag (
  post_id int not null,
  tag_id int not null,
  create_time timestamp null default current_timestamp,
  primary key (post_id, tag_id)
);

-- moderation: reports + actions (MVP)
create table if not exists report (
  id int auto_increment primary key,
  reporter_id int not null,
  target_type int not null,
  target_id int not null,
  reason varchar(64) not null,
  detail varchar(512) default '',
  status int default 0,
  create_time timestamp null default current_timestamp,
  unique key uk_report_dedupe (reporter_id, target_type, target_id)
);

create table if not exists moderation_action (
  id int auto_increment primary key,
  report_id int default null,
  actor_id int not null,
  action varchar(32) not null,
  reason varchar(255) default '',
  duration_seconds int default 0,
  create_time timestamp null default current_timestamp
);

-- bookmarks/subscriptions (MVP)
create table if not exists post_bookmark (
  user_id int not null,
  post_id int not null,
  create_time timestamp null default current_timestamp,
  primary key (user_id, post_id)
);

create table if not exists user_subscription_category (
  user_id int not null,
  category_id int not null,
  create_time timestamp null default current_timestamp,
  primary key (user_id, category_id)
);

-- Compatibility upgrade: add missing column for existing DBs (manual re-run scenario).
set @has_category_id := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'category_id'
);
set @sql := if(@has_category_id = 0, 'alter table discuss_post add column category_id int default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- Compatibility upgrade: add edit/update/delete meta columns for existing DBs.
set @has_update_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'update_time'
);
set @sql := if(@has_update_time = 0, 'alter table discuss_post add column update_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_edit_count := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'edit_count'
);
set @sql := if(@has_edit_count = 0, 'alter table discuss_post add column edit_count int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_deleted_by := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'deleted_by'
);
set @sql := if(@has_deleted_by = 0, 'alter table discuss_post add column deleted_by int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_deleted_reason := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'deleted_reason'
);
set @sql := if(@has_deleted_reason = 0, 'alter table discuss_post add column deleted_reason varchar(255) default ''''', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_deleted_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'discuss_post'
    and column_name = 'deleted_time'
);
set @sql := if(@has_deleted_time = 0, 'alter table discuss_post add column deleted_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_update_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'update_time'
);
set @sql := if(@has_comment_update_time = 0, 'alter table comment add column update_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_edit_count := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'edit_count'
);
set @sql := if(@has_comment_edit_count = 0, 'alter table comment add column edit_count int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_deleted_by := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'deleted_by'
);
set @sql := if(@has_comment_deleted_by = 0, 'alter table comment add column deleted_by int default 0', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_deleted_reason := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'deleted_reason'
);
set @sql := if(@has_comment_deleted_reason = 0, 'alter table comment add column deleted_reason varchar(255) default ''''', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @has_comment_deleted_time := (
  select count(*)
  from information_schema.columns
  where table_schema = database()
    and table_name = 'comment'
    and column_name = 'deleted_time'
);
set @sql := if(@has_comment_deleted_time = 0, 'alter table comment add column deleted_time timestamp null default null', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- Indexes (idempotent)
set @idx_discuss_post_user_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'discuss_post'
    and index_name = 'idx_discuss_post_user_id'
);
set @sql := if(@idx_discuss_post_user_id = 0, 'create index idx_discuss_post_user_id on discuss_post(user_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_discuss_post_category_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'discuss_post'
    and index_name = 'idx_discuss_post_category_id'
);
set @sql := if(@idx_discuss_post_category_id = 0, 'create index idx_discuss_post_category_id on discuss_post(category_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- report indexes (idempotent)
set @idx_report_status := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'report'
    and index_name = 'idx_report_status'
);
set @sql := if(@idx_report_status = 0, 'create index idx_report_status on report(status, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_report_target := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'report'
    and index_name = 'idx_report_target'
);
set @sql := if(@idx_report_target = 0, 'create index idx_report_target on report(target_type, target_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- moderation_action indexes (idempotent)
set @idx_moderation_action_report := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'moderation_action'
    and index_name = 'idx_moderation_action_report'
);
set @sql := if(@idx_moderation_action_report = 0, 'create index idx_moderation_action_report on moderation_action(report_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_moderation_action_actor := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'moderation_action'
    and index_name = 'idx_moderation_action_actor'
);
set @sql := if(@idx_moderation_action_actor = 0, 'create index idx_moderation_action_actor on moderation_action(actor_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- bookmark/subscription indexes (idempotent)
set @idx_post_bookmark_post := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'post_bookmark'
    and index_name = 'idx_post_bookmark_post'
);
set @sql := if(@idx_post_bookmark_post = 0, 'create index idx_post_bookmark_post on post_bookmark(post_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_user_sub_category_user := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'user_subscription_category'
    and index_name = 'idx_user_sub_category_user'
);
set @sql := if(@idx_user_sub_category_user = 0, 'create index idx_user_sub_category_user on user_subscription_category(user_id, create_time)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_comment_entity := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'comment'
    and index_name = 'idx_comment_entity'
);
set @sql := if(@idx_comment_entity = 0, 'create index idx_comment_entity on comment(entity_type, entity_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_post_tag_post_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'post_tag'
    and index_name = 'idx_post_tag_post_id'
);
set @sql := if(@idx_post_tag_post_id = 0, 'create index idx_post_tag_post_id on post_tag(post_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

set @idx_post_tag_tag_id := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'post_tag'
    and index_name = 'idx_post_tag_tag_id'
);
set @sql := if(@idx_post_tag_tag_id = 0, 'create index idx_post_tag_tag_id on post_tag(tag_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- Default categories for dev (idempotent)
insert ignore into category(name, description, position) values
  ('公告', '官方公告/规则', 0),
  ('技术', '技术讨论/问题求助', 10),
  ('兴趣', '兴趣分享/作品展示', 20);


-- --------------------------------------------------------------------
-- Source: 025_schema_social.sql
-- --------------------------------------------------------------------
-- Social schema (community): likes + follows + blocks.

use community;

create table if not exists social_like (
  user_id bigint not null,
  entity_type int not null,
  entity_id bigint not null,
  created_at timestamp not null default current_timestamp,
  primary key (user_id, entity_type, entity_id),
  index idx_like_entity (entity_type, entity_id)
);

-- social_like 扫描索引（idempotent）：用于按 (entity_type, entity_id, user_id) keyset 分页（运维排查/历史遗留 scan 接口）
set @idx_like_entity_user := (
  select count(*)
  from information_schema.statistics
  where table_schema = database()
    and table_name = 'social_like'
    and index_name = 'idx_like_entity_user'
);
set @sql := if(@idx_like_entity_user = 0, 'create index idx_like_entity_user on social_like(entity_type, entity_id, user_id)', 'select 1');
prepare stmt from @sql;
execute stmt;
deallocate prepare stmt;

-- 用户获赞数（计数 SSOT）：由写路径在“新增点赞/取消点赞”时原子增减。
create table if not exists social_user_like_count (
  user_id bigint not null primary key,
  like_count bigint not null default 0,
  updated_at timestamp not null default current_timestamp on update current_timestamp
);

create table if not exists social_follow (
  user_id bigint not null,
  entity_type int not null,
  entity_id bigint not null,
  created_at timestamp not null default current_timestamp,
  primary key (user_id, entity_type, entity_id),
  index idx_follow_followee (user_id, entity_type, created_at, entity_id),
  index idx_follow_follower (entity_type, entity_id, created_at, user_id)
);

create table if not exists social_block (
  user_id bigint not null,
  target_user_id bigint not null,
  created_at timestamp not null default current_timestamp,
  primary key (user_id, target_user_id),
  index idx_block_user_created (user_id, created_at)
);


-- --------------------------------------------------------------------
-- Source: 030_schema_message.sql
-- --------------------------------------------------------------------
-- Message schema (community): message.

use community;

create table if not exists message (
  id int auto_increment primary key,
  from_id int,
  to_id int,
  conversation_id varchar(255),
  content varchar(4000),
  status int default 0,
  create_time timestamp null default current_timestamp
);

create index idx_message_conversation on message(conversation_id);
create index idx_message_to_status on message(to_id, status);


-- --------------------------------------------------------------------
-- Source: 031_schema_im_core.sql
-- --------------------------------------------------------------------
-- IM Core schema (im_core): room + private message (seq-based) + read watermarks.

use im_core;

create table if not exists im_room (
  room_id bigint primary key,
  name varchar(128),
  last_seq bigint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null default current_timestamp on update current_timestamp
);

create table if not exists im_room_member (
  room_id bigint not null,
  user_id int not null,
  role tinyint not null default 0,
  joined_at timestamp null default current_timestamp,
  primary key (room_id, user_id)
);

create index idx_im_room_member_user on im_room_member(user_id, room_id);

create table if not exists im_room_message (
  room_id bigint not null,
  seq bigint not null,
  message_id bigint not null,
  from_user_id int not null,
  content mediumtext not null,
  client_msg_id varchar(64) not null,
  created_at timestamp null default current_timestamp,
  primary key (room_id, seq),
  unique key uk_im_room_message_idempotency (room_id, from_user_id, client_msg_id),
  unique key uk_im_room_message_id (message_id)
);

create index idx_im_room_message_created_at on im_room_message(room_id, created_at, seq);

create table if not exists im_room_read_state (
  room_id bigint not null,
  user_id int not null,
  last_read_seq bigint not null default 0,
  updated_at timestamp null default current_timestamp on update current_timestamp,
  primary key (room_id, user_id)
);

create index idx_im_room_read_state_user on im_room_read_state(user_id, room_id);

create table if not exists im_conversation (
  conversation_id varchar(64) primary key,
  user_a int not null,
  user_b int not null,
  last_seq bigint not null default 0,
  created_at timestamp null default current_timestamp,
  updated_at timestamp null default current_timestamp on update current_timestamp
);

create index idx_im_conversation_users on im_conversation(user_a, user_b, conversation_id);

create table if not exists im_private_message (
  conversation_id varchar(64) not null,
  seq bigint not null,
  message_id bigint not null,
  from_user_id int not null,
  to_user_id int not null,
  content mediumtext not null,
  client_msg_id varchar(64) not null,
  created_at timestamp null default current_timestamp,
  primary key (conversation_id, seq),
  unique key uk_im_private_message_idempotency (conversation_id, from_user_id, client_msg_id),
  unique key uk_im_private_message_id (message_id)
);

create index idx_im_private_message_to on im_private_message(to_user_id, conversation_id, seq);

create table if not exists im_conversation_read_state (
  conversation_id varchar(64) not null,
  user_id int not null,
  last_read_seq bigint not null default 0,
  updated_at timestamp null default current_timestamp on update current_timestamp,
  primary key (conversation_id, user_id)
);

create index idx_im_conversation_read_state_user on im_conversation_read_state(user_id, conversation_id);



-- --------------------------------------------------------------------
-- Source: 040_schema_search.sql
-- --------------------------------------------------------------------
-- Search schema (community).

use community;

-- --------------------------------------------------------------------
-- Source: 090_seed_identity.sql
-- --------------------------------------------------------------------
-- Seed for local dev/demo only.
-- Default user: username=aaa, password=aaa (legacy MD5+salt), status=1 (activated)

use community;

insert into user (id, username, password, salt, email, type, status, header_url, create_time)
values
  (1, 'aaa', 'be5cdc88ad25c5aa86b9a9e1c3573e79', 'salt', 'aaa@example.com', 0, 1, 'http://example.com/a.png', now()),
  (2, 'bbb', 'be5cdc88ad25c5aa86b9a9e1c3573e79', 'salt', 'bbb@example.com', 0, 1, 'http://example.com/b.png', now()),
  (3, 'admin', 'be5cdc88ad25c5aa86b9a9e1c3573e79', 'salt', 'admin@example.com', 1, 1, 'http://example.com/admin.png', now())
on duplicate key update username = values(username);
