services:
  community-app-debug-port:
    image: caddy:2.8-alpine
    container_name: community-app-debug-port
    command:
    - caddy
    - reverse-proxy
    - --from
    - :8080
    - --to
    - community-app-1:8080
    depends_on:
      community-app-1:
        condition: service_started
    ports:
    - 127.0.0.1:12882:8080
  im-core-debug-port:
    image: caddy:2.8-alpine
    container_name: im-core-debug-port
    command:
    - caddy
    - reverse-proxy
    - --from
    - :18082
    - --to
    - im-core-1:18082
    depends_on:
      im-core-1:
        condition: service_started
    ports:
    - 127.0.0.1:18082:18082
  im-realtime-debug-port:
    image: caddy:2.8-alpine
    container_name: im-realtime-debug-port
    command:
    - caddy
    - reverse-proxy
    - --from
    - :18081
    - --to
    - im-realtime-1:18081
    depends_on:
      im-realtime-1:
        condition: service_started
    ports:
    - 127.0.0.1:18081:18081
