services:
  redis:
    image: redis:7-alpine
    mem_limit: ${REDIS_MEM_LIMIT:-192m}
    command:
    - redis-server
    - --appendonly
    - 'yes'
    - --protected-mode
    - 'no'
    - --bind
    - 0.0.0.0
    volumes:
    - redis_node_1_data:/data
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 30
