name: community

networks:
  default:
    ipam:
      config:
      - subnet: ${COMMUNITY_NETWORK_SUBNET:?COMMUNITY_NETWORK_SUBNET is required}

volumes:
  mysql_primary_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_mysql_primary_data
  mysql_replica_1_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_mysql_replica_1_data
  mysql_replica_2_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_mysql_replica_2_data
  redis_node_1_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_redis_node_1_data
  redis_node_2_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_redis_node_2_data
  redis_node_3_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_redis_node_3_data
  redis_node_4_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_redis_node_4_data
  redis_node_5_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_redis_node_5_data
  redis_node_6_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_redis_node_6_data
  garage_node_1_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_garage_node_1_data
  garage_node_2_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_garage_node_2_data
  garage_node_3_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_garage_node_3_data
  kafka_node_1_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_kafka_node_1_data
  kafka_node_2_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_kafka_node_2_data
  kafka_node_3_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_kafka_node_3_data
  elasticsearch_node_1_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_elasticsearch_node_1_data
  elasticsearch_node_2_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_elasticsearch_node_2_data
  elasticsearch_node_3_data:
    name: ${COMMUNITY_VOLUME_NAMESPACE}_elasticsearch_node_3_data
