name: community

volumes:
  mysql_primary_data: {}
  mysql_replica_1_data: {}
  mysql_replica_2_data: {}
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
  garage_data: {}
  garage_1_data: {}
  garage_2_data: {}
  garage_3_data: {}
  kafka_1_data: {}
  kafka_2_data: {}
  kafka_3_data: {}
  es_1_data: {}
  es_2_data: {}
  es_3_data: {}
  observability_logs: {}
