#!/usr/bin/env bash
set -euo pipefail
umask 077

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "usage: $0 <infra-env-file> [output-dir]" >&2
  exit 1
fi

ENV_FILE="$1"
output_dir="${2:-backend/env/generated}"

if [ ! -f "${ENV_FILE}" ]; then
  echo "[render-backend-env] env file not found: ${ENV_FILE}" >&2
  exit 1
fi

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
. "${SCRIPT_DIR}/lib/dotenv.sh"

require_process_env_then_dotenv_value() {
  local variable="$1"
  local resolved
  resolved="$(resolve_process_env_then_dotenv_then_fallback "${variable}")"
  if [ -z "${resolved}" ]; then
    echo "[render-backend-env] ${variable} is required" >&2
    exit 1
  fi
  printf '%s' "${resolved}"
}

quote_env_value() {
  local quoted="$1"
  quoted="${quoted//\\/\\\\}"
  quoted="${quoted//\"/\\\"}"
  quoted="${quoted//\$/\\\$}"
  quoted="${quoted//\`/\\\`}"
  printf '"%s"' "${quoted}"
}

env_line() {
  local variable="$1"
  local resolved="$2"
  printf '%s=%s\n' "${variable}" "$(quote_env_value "${resolved}")"
}

write_common() {
  local server_port="$1"
  cat <<'EOF'
# Generated by ./deploy/deployment.sh render-backend-env --stack infra. Do not edit.
EOF
  env_line SERVER_PORT "${server_port}"
  env_line SPRING_PROFILES_ACTIVE "$(resolve_process_env_then_dotenv_then_fallback SPRING_PROFILES_ACTIVE dev)"
  env_line DEPLOYMENT_ENVIRONMENT "$(resolve_process_env_then_dotenv_then_fallback DEPLOYMENT_ENVIRONMENT development)"
  env_line SERVICE_VERSION local-infra
  env_line OTEL_ENABLED false
  env_line NACOS_SERVER_ADDR "127.0.0.1:$(require_process_env_then_dotenv_value NACOS_HOST_PORT)"
  env_line SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR "127.0.0.1:$(require_process_env_then_dotenv_value NACOS_HOST_PORT)"
  env_line SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR "127.0.0.1:$(require_process_env_then_dotenv_value NACOS_HOST_PORT)"
  env_line SPRING_CLOUD_NACOS_DISCOVERY_IP 127.0.0.1
  env_line NACOS_CONFIG_GROUP "$(resolve_process_env_then_dotenv_then_fallback NACOS_CONFIG_GROUP COMMUNITY)"
  env_line NACOS_NAMESPACE "$(resolve_process_env_then_dotenv_then_fallback NACOS_NAMESPACE)"
}

mkdir -p "${output_dir}"

{
  write_common 18080
  env_line JWT_ACCESS_PUBLIC_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PUBLIC_KEY)"
  env_line JWT_ACCESS_PRIVATE_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PRIVATE_KEY)"
  env_line JWT_SERVICE_HMAC_SECRET "$(require_process_env_then_dotenv_value JWT_SERVICE_HMAC_SECRET)"
  env_line AUTH_PASSWORD_RESET_IDENTIFIER_HMAC_SECRET "$(require_process_env_then_dotenv_value AUTH_PASSWORD_RESET_IDENTIFIER_HMAC_SECRET)"
  env_line AUTH_PASSWORD_RESET_QUOTA_HMAC_SECRET "$(require_process_env_then_dotenv_value AUTH_PASSWORD_RESET_QUOTA_HMAC_SECRET)"
  env_line AUTH_PASSWORD_RESET_PREVIOUS_IDENTIFIER_HMAC_SECRETS "$(resolve_process_env_then_dotenv_then_fallback AUTH_PASSWORD_RESET_PREVIOUS_IDENTIFIER_HMAC_SECRETS)"
  env_line DRIVE_SHARE_TICKET_SECRET "$(require_process_env_then_dotenv_value DRIVE_SHARE_TICKET_SECRET)"
  env_line METRICS_BASIC_AUTH_USERNAME "$(resolve_process_env_then_dotenv_then_fallback METRICS_BASIC_AUTH_USERNAME prometheus)"
  env_line METRICS_BASIC_AUTH_PASSWORD "$(require_process_env_then_dotenv_value METRICS_BASIC_AUTH_PASSWORD)"
  env_line DB_URL "jdbc:mysql://127.0.0.1:$(require_process_env_then_dotenv_value MYSQL_HOST_PORT)/community?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
  env_line DB_USERNAME "$(resolve_process_env_then_dotenv_then_fallback MYSQL_USER community)"
  env_line DB_PASSWORD "$(require_process_env_then_dotenv_value MYSQL_PASSWORD)"
  env_line SPRING_DATA_REDIS_HOST 127.0.0.1
  env_line SPRING_DATA_REDIS_PORT "$(require_process_env_then_dotenv_value REDIS_HOST_PORT)"
  env_line KAFKA_BOOTSTRAP_SERVERS "127.0.0.1:$(require_process_env_then_dotenv_value KAFKA_HOST_PORT)"
  env_line ELASTICSEARCH_URIS "http://127.0.0.1:$(require_process_env_then_dotenv_value ELASTICSEARCH_HOST_ACCESS_PORT)"
  env_line SPRING_MAIL_HOST 127.0.0.1
  env_line SPRING_MAIL_PORT "$(require_process_env_then_dotenv_value MAILHOG_SMTP_HOST_PORT)"
  env_line SPRING_MAIL_USERNAME "$(resolve_process_env_then_dotenv_then_fallback SPRING_MAIL_USERNAME)"
  env_line SPRING_MAIL_PASSWORD "$(resolve_process_env_then_dotenv_then_fallback SPRING_MAIL_PASSWORD)"
  env_line OSS_CLIENT_BASE_URL http://127.0.0.1:18090
  env_line WALLET_TEST_CREDITS_ENABLED "$(resolve_process_env_then_dotenv_then_fallback WALLET_TEST_CREDITS_ENABLED true)"
  env_line WALLET_TEST_CREDIT_GRANT_ENABLED "$(resolve_process_env_then_dotenv_then_fallback WALLET_TEST_CREDIT_GRANT_ENABLED true)"
  env_line WALLET_TEST_CREDIT_DISCARD_ENABLED "$(resolve_process_env_then_dotenv_then_fallback WALLET_TEST_CREDIT_DISCARD_ENABLED true)"
} >"${output_dir}/community-app.env"

{
  write_common 18090
  env_line JWT_ACCESS_PUBLIC_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PUBLIC_KEY)"
  env_line JWT_SERVICE_HMAC_SECRET "$(require_process_env_then_dotenv_value JWT_SERVICE_HMAC_SECRET)"
  env_line METRICS_BASIC_AUTH_USERNAME "$(resolve_process_env_then_dotenv_then_fallback METRICS_BASIC_AUTH_USERNAME prometheus)"
  env_line METRICS_BASIC_AUTH_PASSWORD "$(require_process_env_then_dotenv_value METRICS_BASIC_AUTH_PASSWORD)"
  env_line OSS_DB_URL "jdbc:mysql://127.0.0.1:$(require_process_env_then_dotenv_value MYSQL_HOST_PORT)/community_oss?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
  env_line OSS_DB_USERNAME "$(resolve_process_env_then_dotenv_then_fallback OSS_MYSQL_USER community_oss)"
  env_line OSS_DB_PASSWORD "$(require_process_env_then_dotenv_value OSS_MYSQL_PASSWORD)"
  env_line OSS_OBJECT_STORE_MODE garage
  env_line OSS_OBJECT_STORE_ENDPOINT "http://127.0.0.1:$(require_process_env_then_dotenv_value GARAGE_S3_HOST_PORT)"
  env_line OSS_OBJECT_STORE_ACCESS_KEY "$(require_process_env_then_dotenv_value GARAGE_DEFAULT_ACCESS_KEY)"
  env_line OSS_OBJECT_STORE_SECRET_KEY "$(require_process_env_then_dotenv_value GARAGE_DEFAULT_SECRET_KEY)"
  env_line OSS_OBJECT_STORE_BUCKET "$(resolve_process_env_then_dotenv_then_fallback GARAGE_DEFAULT_BUCKET community-oss)"
  env_line OSS_OBJECT_STORE_REGION "$(resolve_process_env_then_dotenv_then_fallback OSS_OBJECT_STORE_REGION garage)"
  env_line OSS_OBJECT_STORE_PATH_STYLE true
  env_line OSS_PUBLIC_BASE_URL "$(resolve_process_env_then_dotenv_then_fallback OSS_PUBLIC_BASE_URL http://127.0.0.1:12880)"
} >"${output_dir}/community-oss.env"

{
  write_common "$(require_process_env_then_dotenv_value NGINX_API_PORT)"
  env_line JWT_ACCESS_PUBLIC_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PUBLIC_KEY)"
  env_line METRICS_BASIC_AUTH_USERNAME "$(resolve_process_env_then_dotenv_then_fallback METRICS_BASIC_AUTH_USERNAME prometheus)"
  env_line METRICS_BASIC_AUTH_PASSWORD "$(require_process_env_then_dotenv_value METRICS_BASIC_AUTH_PASSWORD)"
  env_line SPRING_DATA_REDIS_HOST 127.0.0.1
  env_line SPRING_DATA_REDIS_PORT "$(require_process_env_then_dotenv_value REDIS_HOST_PORT)"
  env_line GATEWAY_TRUSTED_PROXY_ENABLED false
  env_line GATEWAY_WS_PROXY_AUTH_REQUIRED true
} >"${output_dir}/community-gateway.env"

{
  write_common 18083
  env_line JWT_ACCESS_PUBLIC_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PUBLIC_KEY)"
  env_line IM_SESSION_TICKET_HMAC_SECRET "$(require_process_env_then_dotenv_value IM_SESSION_TICKET_HMAC_SECRET)"
  env_line IM_SESSION_TICKET_ISSUER "$(resolve_process_env_then_dotenv_then_fallback IM_SESSION_TICKET_ISSUER community-im-gateway)"
  env_line IM_SESSION_TICKET_AUDIENCE "$(resolve_process_env_then_dotenv_then_fallback IM_SESSION_TICKET_AUDIENCE im-realtime)"
  env_line IM_GATEWAY_PUBLIC_WS_URL "$(resolve_process_env_then_dotenv_then_fallback IM_GATEWAY_PUBLIC_WS_URL ws://127.0.0.1:12880/ws/im)"
  env_line COMMUNITY_METRICS_BASIC_AUTH_USERNAME "$(resolve_process_env_then_dotenv_then_fallback METRICS_BASIC_AUTH_USERNAME prometheus)"
  env_line COMMUNITY_METRICS_BASIC_AUTH_PASSWORD "$(require_process_env_then_dotenv_value METRICS_BASIC_AUTH_PASSWORD)"
} >"${output_dir}/community-im-gateway.env"

{
  write_common 18082
  env_line JWT_ACCESS_PUBLIC_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PUBLIC_KEY)"
  env_line JWT_SERVICE_HMAC_SECRET "$(require_process_env_then_dotenv_value JWT_SERVICE_HMAC_SECRET)"
  env_line IM_CORE_DB_URL "jdbc:mysql://127.0.0.1:$(require_process_env_then_dotenv_value MYSQL_HOST_PORT)/im_core?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
  env_line IM_CORE_DB_USER "$(resolve_process_env_then_dotenv_then_fallback IM_MYSQL_USER im_core)"
  env_line IM_CORE_DB_PASSWORD "$(require_process_env_then_dotenv_value IM_MYSQL_PASSWORD)"
  env_line KAFKA_BOOTSTRAP_SERVERS "127.0.0.1:$(require_process_env_then_dotenv_value KAFKA_HOST_PORT)"
} >"${output_dir}/im-core.env"

{
  write_common 18081
  env_line JWT_ACCESS_PUBLIC_KEY "$(require_process_env_then_dotenv_value JWT_ACCESS_PUBLIC_KEY)"
  env_line JWT_SERVICE_HMAC_SECRET "$(require_process_env_then_dotenv_value JWT_SERVICE_HMAC_SECRET)"
  env_line IM_SESSION_TICKET_HMAC_SECRET "$(require_process_env_then_dotenv_value IM_SESSION_TICKET_HMAC_SECRET)"
  env_line IM_SESSION_TICKET_ISSUER "$(resolve_process_env_then_dotenv_then_fallback IM_SESSION_TICKET_ISSUER community-im-gateway)"
  env_line IM_SESSION_TICKET_AUDIENCE "$(resolve_process_env_then_dotenv_then_fallback IM_SESSION_TICKET_AUDIENCE im-realtime)"
  env_line KAFKA_BOOTSTRAP_SERVERS "127.0.0.1:$(require_process_env_then_dotenv_value KAFKA_HOST_PORT)"
  env_line SPRING_DATA_REDIS_HOST 127.0.0.1
  env_line SPRING_DATA_REDIS_PORT "$(require_process_env_then_dotenv_value REDIS_HOST_PORT)"
  env_line IM_REALTIME_WORKER_ID im-realtime-local
  env_line IM_ROOM_FANOUT_WORKER_INBOX_SLOT 0
  env_line IM_SESSION_WS_BASE_URL ws://127.0.0.1:18081/internal/ws/im
} >"${output_dir}/im-realtime.env"

echo "[render-backend-env] wrote service env files to ${output_dir}"
