services:
  mock-data-studio:
    environment:
      MOCK_DATA_STUDIO_DB_URL: mysql://${DB_PRIMARY_HOST:-mysql}:3306/community
    depends_on:
      mysql:
        condition: service_healthy
      mock-data-studio-db-bootstrap:
        condition: service_completed_successfully
      community-app:
        condition: service_started
      im-core:
        condition: service_started
